@token=<your token here>

POST http://localhost:8000/login
Content-Type: application/json

{
    "username": "user1",
    "password": "pass1"
}

###

POST http://localhost:8000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

GET http://localhost:8000/
Authorization: Bearer {{token}}

###

GET http://localhost:8000/admin
Authorization: Bearer {{token}}
